// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNXx0xWJI675JzwJafYmpY0jirj1zQFHE',
    appId: '1:832544792214:web:f087eddc40eb37e33c2cb7',
    messagingSenderId: '832544792214',
    projectId: 'urchat-d4aa3',
    authDomain: 'urchat-d4aa3.firebaseapp.com',
    storageBucket: 'urchat-d4aa3.firebasestorage.app',
    measurementId: 'G-Q4WPN0C7NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKKBwPEcTtPEVuyDBbFBn1X1CmuMxaOY',
    appId: '1:832544792214:android:f8e9a3681814d1753c2cb7',
    messagingSenderId: '832544792214',
    projectId: 'urchat-d4aa3',
    storageBucket: 'urchat-d4aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqT_-2GEIf3Qi-RjGH68XF7ZiCPfukfXk',
    appId: '1:832544792214:ios:474d1a71c20259733c2cb7',
    messagingSenderId: '832544792214',
    projectId: 'urchat-d4aa3',
    storageBucket: 'urchat-d4aa3.firebasestorage.app',
    iosBundleId: 'com.example.urchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqT_-2GEIf3Qi-RjGH68XF7ZiCPfukfXk',
    appId: '1:832544792214:ios:474d1a71c20259733c2cb7',
    messagingSenderId: '832544792214',
    projectId: 'urchat-d4aa3',
    storageBucket: 'urchat-d4aa3.firebasestorage.app',
    iosBundleId: 'com.example.urchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNXx0xWJI675JzwJafYmpY0jirj1zQFHE',
    appId: '1:832544792214:web:2fad676c3e556af33c2cb7',
    messagingSenderId: '832544792214',
    projectId: 'urchat-d4aa3',
    authDomain: 'urchat-d4aa3.firebaseapp.com',
    storageBucket: 'urchat-d4aa3.firebasestorage.app',
    measurementId: 'G-2HWRD0F2E7',
  );
}
